# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo 'init script' # runs during prebuild
      npm install
      wget https://www.apache.org/dyn/closer.cgi?filename=/activemq/5.17.1/apache-activemq-5.17.1-bin.tar.gz&action=download
      ls -l
      gunzip apache-activemq-5.17.1-bin.tar.gz
      ls -lrt
    command: echo 'start script'
   

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
