

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

tasks:
  - name: "ActiveMQ"
    before: |
        echo "PATH=${PATH}" 
    init: |
        npm install mqtt 
        cd estate
        npm install  
    command: |      
        activemq start
        gp sync-done activeMqReady             
  - name: "Monitor"
    command: |
        clear
        gp sync-await activeMqReady
        activemq status
        sleep 1 # even though activemq status is good it's not quite ready!
        # watch for temperatures falling below 20 degrees for more than 30 seconds
        node homeMonitor.js 20 30       
  - name: "Thermostat-01-01"
    command: |
        clear
        echo "group 01, property 01"
        node thermostat.js 01 01 "The Willows"
  - name: "Thermostat-01-02"
    command: |
        clear
        echo "group 01, property 02"
        node thermostat.js 01 02 "The Oaks"
  - name: "Thermostat-02-01"
    command: |
        clear
        echo "group 02, property 01"
        node thermostat.js 02 01 "Astoria"
       
